- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- test-project/README.md
- test-project/build.gradle
That enables running the test project as a stand-alone project as well as using it to smoke test an unpublished plugin
> Made plugin resolution in test project conditional

- README.md
- test-project/greeter.provider.test/src/test/java/tests/GreeterTest.java
- test-project/greeter.provider/src/test/java/examples/greeter/FriendlyTest.java
The `public` modifier is no longer needed when using JUnit Jupiter.
> Prune public modifier from tests

- src/main/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTestTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/ModuleInfoTestHelper.java
- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- test-project/greeter.provider/src/test/java/examples/greeter/ScriptingTest.java
- test-project/greeter.provider/src/test/java/module-info.test
Support `module-info.test` configuration files.
Kudos to @marcphilipp for helping with some Gradle-foo.
Fixes #17
> Support module-info.test

- src/main/java/org/javamodularity/moduleplugin/ModuleSystemPlugin.java
- src/main/java/org/javamodularity/moduleplugin/tasks/JavadocTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- test-project/build.gradle
Add `--module-path` for Javadoc task.
This does not support adding extra `--add-modules` yet.
> fix for javadoc

- README.md
This updates the `moduleplugin` version in the example and changes the example project version to `1.0-SNAPSHOT` to emphasize that it's not related to the plugin version.
> update example build.gradle in README

- src/main/java/org/javamodularity/moduleplugin/ModuleSystemPlugin.java
- src/main/java/org/javamodularity/moduleplugin/tasks/RunTask.java
This PR is a fix for issue #23. It works by removing the `--module` argument from the java command when the project is not defined as a module.
> also apply run task when no module is used in the project

- build.gradle
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- test-project/README.md
- test-project/local_maven_build.gradle
- test-project/local_maven_settings.gradle
- test-project/smoke_test_build.gradle
- test-project/smoke_test_settings.gradle
one to be used independently, one to be used against a locally published plugin, and another one for the smoke test.
Enabled output forwarding in the smoke test so the output doesnt have to be captured independently.
Updated the docs
> Split a test project into 3 separate test projects

- src/main/java/org/javamodularity/moduleplugin/tasks/RunTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- test-project/greeter.provider/src/main/java/examples/greeter/Friendly.java
- test-project/greeter.provider/src/main/resources/greeting.txt
- test-project/greeter.runner/src/main/java/examples/Runner.java
> --patch-module so that resources are loaded correctly in tests

- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
Tested on a Windows 7 machine:
Running
```bash
../gradlew clean build
```
from `test-project` triggered the reported error:
```
> Task :greeter.provider:test FAILED
Error occurred during initialization of boot layer
java.lang.ExceptionInInitializerError
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 116: C:\cygwin64\home\90019249\repos-external\gradle-modules-plugin\test-project\greeter.provider\build\classes\java\test:C:\cygwin64\home\90019249\repos-external\gradle-modules-plugin\test-project\greeter.provider\build\resources\main:C:\cygwin64\home\90019249\repos-external\gradle-modules-plugin\test-project\greeter.provider\build\resources\test
```
After running
```bash
./gradlew publishToMavenLocal
```
from the root directory, running
```bash
../gradlew -c …
```
> Fixed #36 by replacing ":" with File.pathSeparator

- src/main/java/org/javamodularity/moduleplugin/tasks/RunTask.java
This PR removes the --patch-modules JVM argument when the gradle project is not modular, which allows the project to run.
> only add --patch-modules jvm argument when the project is modular

- src/main/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutator.java
- test-project-kotlin/greeter.provider/build.gradle.kts
- test-project-kotlin/greeter.provider/src/test/kotlin/examples/greeter/ScriptingTest.kt
- test-project-kotlin/greeter.provider/src/test/kotlin/module-info.test
- test-project/greeter.provider/build.gradle
- test-project/greeter.provider/src/test/java/examples/greeter/ScriptingTest.java
- test-project/greeter.provider/src/test/java/module-info.test
This PR:
- extends `greeter.provider` to catch the problem raised by this issue.
- removes the call to `ModuleInfoTestHelper.mutateArgs()` from `CompileJavaTaskMutator`
> issue #53: apply module-info.test only to test-related tasks

- build.gradle
JavaParser uses the so-called [pragmatic versioning](https://javaparser.org/pragmatic-versioning/), which means that breaking changes may occur (and they do occur) even between patch releases.
This PR relocates the JavaParser classes (using the Shadow plugin) to prevent incompatibilities with other tools.
> Relocate JavaParser classes

- src/main/java/org/javamodularity/moduleplugin/internal/PatchModuleResolver.java
- src/main/java/org/javamodularity/moduleplugin/internal/StreamHelper.java
- src/main/java/org/javamodularity/moduleplugin/internal/TaskOption.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTestTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/JavadocTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/ModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/tasks/PatchModuleExtension.java
- src/main/java/org/javamodularity/moduleplugin/tasks/RunTaskMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/StartScriptsMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- src/test/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutatorTest.java
Fixes #89.
There were two tasks that had no support implemented for `--add-exports`, etc. (#74):
1. `RunTask`
2. `JavadocTask`
In order to accomodate the `JavadocTask`, I introduced a new class for holding the flag-value pairs (`TaskOption`).
After introducing it, I decided it's worth refactoring all such flag-value pairs to `TaskOption`, hence so many changes (sorry). I like the end result, though :smiley:
> Fix #89: Support for all module options in RunTask and JavadocTask

- src/main/java/org/javamodularity/moduleplugin/internal/TaskOption.java
- src/test/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutatorTest.java
Sorry for trouble, but when I woke up today, I realized I introduced a regression by [disallowing spaces in `TaskOption`'s `value`](https://github.com/java9-modularity/gradle-modules-plugin/blob/4014f02a411fc4f3a4981bcc69677e10e892ab30/src/main/java/org/javamodularity/moduleplugin/internal/TaskOption.java#L31).
Spaces should definitely be allowed there:
- when they're fed to `javac`, `javadoc`, etc., they're enclosed in quotes ([example](https://github.com/gradle/gradle/blob/9e5363f5dacf64cf6eb5377493354a630e575bd1/subprojects/language-java/src/main/java/org/gradle/external/javadoc/internal/JavadocOptionFileWriterContext.java#L64))
- as it is now, everyone who'll try to use the plugin with a directory structure that contains a space may have their build fail
This PR fixes this regression. …
> Fixed a regression in TaskOption

- README.md
- src/main/java/org/javamodularity/moduleplugin/ModuleSystemPlugin.java
- src/main/java/org/javamodularity/moduleplugin/extensions/CompileModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/extensions/CompileTestModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/extensions/JavadocModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/extensions/ModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/extensions/PatchModuleExtension.java
- src/main/java/org/javamodularity/moduleplugin/extensions/RunModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/extensions/RuntimeModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/extensions/TestModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/internal/PatchModuleResolver.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTestTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/JavadocTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/MergeClassesHelper.java
- src/main/java/org/javamodularity/moduleplugin/tasks/RunTaskMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/StartScriptsMutator.java
- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- src/test/java/org/javamodularity/moduleplugin/tasks/CompileJavaTaskMutatorTest.java
- test-project-kotlin/greeter.api/build.gradle.kts
- test-project-kotlin/greeter.provider/build.gradle.kts
- test-project-kotlin/greeter.runner/build.gradle.kts
Fixes #80:
> 1. Moving extensions from `tasks` subpackage to `extensions` subpackage
> 2. Extracting dedicated `*ModuleOptions` interfaces for every task
> 3. Limiting `ModuleOptions.addOpens` to `test` and `run` tasks only
> Note: (1) and (2) are *potentially breaking changes for Kotlin DSL*.
I'd prefer this to be merged without squashing if you agree.
> Some API refactorings (fixes #80)

- src/main/java/org/javamodularity/moduleplugin/internal/CompileModuleInfoHelper.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileModuleInfoTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTask.java
Fixes #107.
I haven't added any extra automated tests for it, but I have verified manually (by changing `LOGGER.debug` to `LOGGER.lifecycle`) that the dependencies are indeed being added as expected:
- for `test-project-groovy`:
```text
> Configure project :
Project :greeter.api => 'greeter.api' Java module
Project :greeter.javaexec => 'greeter.javaexec' Java module
Project :greeter.provider => 'greeter.provider' Java module
Project :greeter.provider.test => 'greeter.provider.test' Java module
Project :greeter.runner => 'greeter.runner' Java module
Project :greeter.startscripts => 'greeter.startscripts' Java module
> Configure project :greeter.javaexec
task ':greeter.javaexec:compileModuleInfoJava'.dependsOn(task ':greeter.api:compileModuleInfoJava')
> Configure project :greeter.provider …
```
> Add dependencies on `compileModuleInfoJava` of dependent projects

- README.md
I propose a smaller and newer syntax for the plugin declaration in the demo code of the README.md.
Replace the legacy Buildscript block:
```groovy
buildscript {
repositories {
maven {
url "https://plugins.gradle.org/m2/"
}
}
dependencies {
classpath "org.javamodularity:moduleplugin:1.6.0"
}
}
```
by Plugins (apply false):
```groovy
plugins {
id 'org.javamodularity.moduleplugin' version '1.6.0' apply false
}
```
Available since gradle 4.10.
See https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> Update README.md - Replace the legacy Buildscript block by Plugins (apply false)

- src/main/java/org/javamodularity/moduleplugin/TestEngine.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTestTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- test-project/build.gradle
- test-project/gradle.properties
Mockito, EasyMock, AssertJ, JUnit 5.5.x
This PR is meant to address two related issues:
1. The plugin doesn't work correctly with JUnit 5.5.x
2. The plugin is missing support for certain common testing components, and cannot accommodate multiple testing components being in scope at the same time
For example, JUnit 5 is designed to live comfortably in the same project with JUnit 4. Additionally, tools like Mockito, EasyMock, and AssertJ are commonly used.
> Adding support for additional test frameworks

- test-project-groovy/gradle.properties
- test-project-kotlin/build.gradle.kts
- test-project-kotlin/gradle.properties
- test-project-mixed/build.gradle
- test-project-mixed/gradle.properties
- test-project/gradle.properties
Not all sample projects were updated for the new JUnit 5.5.x+ support
> Fix sample projects for JUnit 5.5.x support

- src/main/java/org/javamodularity/moduleplugin/TestEngine.java
Add support for automatically detecting a JUnit 5 Parameters dependency and configuring the test configurations accordingly.
Fixes #175
> Add support for JUnit 5 Params

- build.gradle
This PR just sets a `duplicatesStrategy = 'exclude'` to deal with the issue.
> issue #192: Plugin build fails with Gradle 7

- build.gradle
This simple PR just adds the two missing dependencies.
> issue #194: Plugin tests do not compile due to missing Guava dependencies

- src/main/java/org/javamodularity/moduleplugin/tasks/CompileModuleInfoTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
Hello 👋 
Thanks for providing this Gradle plugin, it helps me a lot to keep build scripts simple even with module support. Here I have a suggestion to support Gradle 7.2:
I'm using the gradle-modules-plugin with Gradle 7.2, and found the [following warnings during the build](https://github.com/jspecify/jspecify/runs/3443340180#step:6:36):
```
Execution optimizations have been disabled for task ':jar' to ensure correctness due to the following reasons:
- Additional action of task ':jar' was implemented by the Java lambda 'org.javamodularity.moduleplugin.tasks.CompileModuleInfoTask$$Lambda$813/0x0000000100832c40'. Reason: Using Java lambdas is not supported as task inputs. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implementation_unknown for more details …
```
> Resolve warning in Gradle 7.2

- src/main/java/org/javamodularity/moduleplugin/ModuleName.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileModuleInfoTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
Currently there are several dependencies on deprecated API. Gradle 6.1 and 7.1 provide better replacements, so this PR suggests introducing these APIs.
> Replace usage of outdated Gradle API

- .github/workflows/build.yml
- .github/workflows/publish.yml
Hello folks,
I want to suggest this PR which introduces major updates to GitHub Actions used in the workflow:
1. [`actions/checkout` released v3](https://github.com/actions/checkout/releases/tag/v3.0.0) which is using the latest Node.JS as its default runtime. Current Node.JS in runtime is [v12, which will be EOL at this April](https://nodejs.org/en/about/releases/), so better to update it.
2. `actions/setup-java` released v2 which supports the [dependency caching](https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/). It lets us remove the `actions/cache` from the workflow, and make the workflow definition simple and short.
Hope that this PR helps you to keep the development environment updated and secure! :)
> ci: Update GitHub Actions

- src/main/java/org/javamodularity/moduleplugin/extensions/DefaultModularityExtension.java
- test-project/greeter.toolchain/build.gradle
- test-project/greeter.toolchain/src/main/java/examples/greeter/api/Greeter.java
- test-project/greeter.toolchain/src/main/java/module-info.java
- test-project/settings.gradle
Gradle 6.7+ provides the [Toolchains for JVM projects](https://docs.gradle.org/7.4/userguide/toolchains.html), which makes it possible to specify which Java we use to compile the project. refs #187
Currently gradle-modules-plugin has two potential problems around this toolchain feature:
1. By default the toolchain feature adds the `--release` option via `javaCompile.options.release` property, and it conflicts with the `--release` option set by this plugin. Fixed by the commit 6163723598d0bd5ff0748672507cd934b169718f
```
* What went wrong:
Execution failed for task :greeter.toolchain:compileJava.
> Cannot specify --release via `CompileOptions.compilerArgs` when using `JavaCompile.release`.
```
2. When a toolchain is enabled, the version of java compiler will be not the version of JVM …
> Provide better support for toolchains for JVM projects

- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
Running locally with JDK-14+ results in a compilation error when running `ModulePluginSmokeTest` due to https://github.com/gradle/gradle/issues/10248.
Rather than requiring contributors to install _really_ old JDKs to run tests, lets provide an easy way to _locally_ comment out the old 5.x Gradle versions.  The full version tests will still run on the build server.
(This also makes it a lot easier to locally reduce the number of versions being tested during development)
> Make it easier to test locally

- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTestTask.java
- src/main/java/org/javamodularity/moduleplugin/tasks/ModuleInfoTestHelper.java
- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- src/test/java/org/javamodularity/moduleplugin/tasks/ModuleInfoTestHelperTest.java
- test-project/greeter.provider.test/src/test/java/module-info.test
fixes: https://github.com/java9-modularity/gradle-modules-plugin/issues/211
Avoids ``--add-opens has no effect at compile time` warnings when compiling test code by filtering out
`--add-opens` entries from the `module-info.test` file when executing the `compileTestJava` task.
This is achieved by filtering out any `--add-opens` lines and the subsequent line, which contains the _opens_ to add, in the `ModuleInfoTestHelper` class.
> Avoid warning about `--add-opens` from `compileTestJava` task

- src/main/java/org/javamodularity/moduleplugin/tasks/MergeClassesHelper.java
This addresses Issue #221 with the same check to guard access to the deprecated property as found at https://github.com/java9-modularity/gradle-modules-plugin/blob/cc1f0fdc1e6aadfb1054ae2373fd10b1d5da2b6b/src/main/java/org/javamodularity/moduleplugin/tasks/CompileModuleInfoTask.java#L104
> Avoid reference to deprecated property. (#221)

- src/main/java/org/javamodularity/moduleplugin/tasks/ModularJavaExec.java
Seems to fix the issue, Gradle >= 8 stopped complaining and all unit tests passed.
> Fix for java9-modularity#224

- src/main/java/org/javamodularity/moduleplugin/tasks/TestTask.java
- test-project-kotlin/greeter.provider.test/build.gradle.kts
- test-project-kotlin/greeter.provider.test/src/test/kotlin/tests/GreeterTest.kt
fixes: https://github.com/java9-modularity/gradle-modules-plugin/issues/227
Enhance `TestTask` to patch-in additional resource directories containing generated resources, as added via `org.gradle.api.tasks.SourceSetOutput.dir()` methods, so that all resources are accessible when running unit tests.
> Patch-in generated resources during testing

- build.gradle
Updates to the latest `com.gradle.plugin-publish` plugin, which required updating `com.github.johnrengelman.shadow` from `5.0.0` to `7.1.2`.
It's not possible to update to a later version of `com.github.johnrengelman.shadow` as v8+ requires Gradle 8+, which would mean dropping support for earlier versions of Gradle.  One for another day.
Replaces https://github.com/java9-modularity/gradle-modules-plugin/pull/237
> Bump com.gradle.plugin-publish to 1.2.1 AND com.github.johnrengelman.shadow to 7.1.2

- README.md
- src/main/java/org/javamodularity/moduleplugin/tasks/MergeClassesTask.java
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
fixes: https://github.com/java9-modularity/gradle-modules-plugin/issues/258
Gradle 7.6 is executing tasks in a different order, with `mergeClasses` being run _after_ `compileTestJava`.   This results in `compileTestJava` failing as it can't find the `module-info.class` which is generated by `mergeClasses`.
Fix looks to be to have the `compileTestJava` task, i.e. `JavaPlugin.COMPILE_TEST_JAVA_TASK_NAME`, depend on the `mergeClasses` task. Thereby ensuring `mergeClasses` runs first and the `module-info.class` is available to `compileTestJava`.
It is possible/likely that the `JavaPlugin.TEST_TASK_NAME` task, i.e. `test` task, no longer needs to depend on `mergeClasses`.  However, removing it may cause problems if there are other tasks run by `test` that require the output of `mergeClasses`. …
> Fix compatibility issue with Gradle 7.6+

- README.md
- build.gradle
- src/test/java/org/javamodularity/moduleplugin/ModulePluginSmokeTest.java
- test-project-groovy/gradle.properties
- test-project-kotlin-pre-1-7/build.gradle.kts
- test-project-kotlin-pre-1-7/gradle.properties
- test-project-kotlin/build.gradle.kts
- test-project-kotlin/gradle.properties
- test-project-kotlin/greeter.startscripts/build.gradle.kts
- test-project-mixed/gradle.properties
- test-project/gradle.properties
fixes: https://github.com/java9-modularity/gradle-modules-plugin/issues/260
Aside from the incompatibility between Gradle 8 and versions of JUnit prior to 5.8.0, no other issues were found.
> Update tests to cover Gradle 8

- src/main/java/org/javamodularity/moduleplugin/extensions/CompileTestModuleOptions.java
- src/main/java/org/javamodularity/moduleplugin/tasks/CompileTestTask.java
- test-project-groovy/build.gradle
- test-project-kotlin/build.gradle.kts
The README section for [Fall-back to classpath mode](https://github.com/java9-modularity/gradle-modules-plugin?tab=readme-ov-file#fall-back-to-classpath-mode) states that using the Kotlin DSL, you can enable classpath mode while running tests with:
```kts
tasks {
compileTestJava {
extensions.configure(CompileTestModuleOptions::class) {
compileOnClasspath = true
}
}
}
```
In fact, in version 1.8.15 of the plugin, you have to write `isCompileOnClasspath = true`.  The reason for this is that the accessor needs to be called `getCompileOnClasspath()` for it to be treated as a property in Kotlin.
Note that this doesn't affect the Groovy DSL, and that `TestModuleOptions` works as documented for both Kotlin and Groovy.
I've adjusted the tests to demonstrate the problem, implemented a fix, and …
> Make CompileTestModuleOptions consistent with documentation
